services:
  # =============================================================================
  # PREMIUM SAAS WEB SERVICE (Primary)
  # =============================================================================
  - type: web
    name: claxis-web-production
    env: node
    plan: standard
    region: frankfurt  # EU data residency compliance
    numInstances: 2    # High availability for premium tier
    healthCheckPath: /api/health
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      # App Configuration
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: claxis-web-production
          property: host
      - key: NEXT_PUBLIC_APP_NAME
        value: Gemini Salon AI
      
      # Database (Supabase EU)
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      
      # WhatsApp Business API (Production)
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      
      # Instagram Business API (Production)
      - key: INSTAGRAM_ACCESS_TOKEN
        sync: false
      - key: INSTAGRAM_APP_SECRET
        sync: false
      - key: INSTAGRAM_PAGE_ID
        sync: false
      - key: INSTAGRAM_WEBHOOK_VERIFY_TOKEN
        sync: false
      
      # AI Services
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      
      # Redis (Managed by Render)
      - key: REDIS_URL
        fromService:
          type: redis
          name: claxis-redis-production
          property: connectionString
      
      # Authentication
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: claxis-web-production
          property: host
      
      # EU Compliance
      - key: DATA_REGION
        value: eu-central-1
      - key: DATA_RESIDENCY
        value: frankfurt
      - key: GDPR_DPO_EMAIL
        sync: false
      
      # Premium Performance Settings
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: 100

  # =============================================================================
  # PREMIUM SAAS WORKER SERVICE (Background Processing)
  # =============================================================================
  - type: worker
    name: claxis-worker-production
    env: node
    plan: standard
    region: frankfurt  # EU data residency compliance
    numInstances: 1    # Single worker for cost optimization
    buildCommand: npm run build
    startCommand: node worker.js
    envVars:
      # Share all environment variables with web service
      - key: NODE_ENV
        value: production
      
      # Database (Supabase EU)
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      
      # WhatsApp Business API
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      
      # AI Services
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      
      # Redis Connection
      - key: REDIS_URL
        fromService:
          type: redis
          name: claxis-redis-production
          property: connectionString
      
      # EU Compliance
      - key: DATA_REGION
        value: eu-central-1
      - key: DATA_RESIDENCY
        value: frankfurt

  # =============================================================================
  # STAGING ENVIRONMENT (Testing & Development)
  # =============================================================================
  - type: web
    name: claxis-web-staging
    env: node
    plan: starter
    region: frankfurt
    numInstances: 1
    healthCheckPath: /api/health
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      # Staging Configuration
      - key: NODE_ENV
        value: development
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: claxis-web-staging
          property: host
      - key: NEXT_PUBLIC_APP_NAME
        value: Gemini Salon AI (Staging)
      
      # Staging Database
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false  # Use staging Supabase project
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      
      # Staging WhatsApp (Separate Meta App)
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false  # Different staging tokens
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      
      # Staging Redis
      - key: REDIS_URL
        fromService:
          type: redis
          name: claxis-redis-staging
          property: connectionString
      
      # Debug Settings
      - key: NEXT_PUBLIC_DEBUG_MODE
        value: true
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: 50

databases:
  # =============================================================================
  # REDIS FOR QUEUE SYSTEM (Production)
  # =============================================================================
  - type: redis
    name: claxis-redis-production
    plan: starter
    region: frankfurt
    maxmemoryPolicy: allkeys-lru

  # =============================================================================
  # REDIS FOR STAGING
  # =============================================================================
  - type: redis
    name: claxis-redis-staging  
    plan: starter
    region: frankfurt
    maxmemoryPolicy: allkeys-lru

# =============================================================================
# PREMIUM SAAS DEPLOYMENT NOTES
# =============================================================================
# 
# Architecture:
# - Web Service: Handles HTTP requests, webhook ingestion (fast <2s response)
# - Worker Service: Background processing (AI, database operations, business logic)
# - Redis: Queue system for reliable message processing
# - Separate staging environment for safe testing
#
# EU Compliance:
# - All services deployed in Frankfurt region
# - GDPR-compliant data processing
# - Data residency in EU
#
# Premium Performance:
# - 2x web instances for high availability  
# - Optimized worker for background processing
# - Redis for enterprise-grade queue reliability
# - Health monitoring endpoints
#
# Security:
# - All secrets managed via Render environment variables
# - Separate production/staging credentials
# - No secrets in configuration files
#
# Cost Optimization:
# - Single worker instance (can scale if needed)
# - Starter Redis plans (can upgrade)
# - Efficient resource allocation for €299.99/month tier